use_frameworks!

platform :ios, '15.0'

target 'CoECyberBankDynetrace_Example' do
  pod 'CoECyberBankDynetrace', :path => '../'

  target 'CoECyberBankDynetrace_Tests' do
    inherit! :search_paths

    
  end
end
